[server]
host-name=gestaorls
domain-name=local
browse-domains=local
use-ipv4=yes
use-ipv6=no
# Escuta apenas nas interfaces físicas reais (LAN + ZeroTier)
allow-interfaces=eno1,ztkti7cao5
deny-interfaces=docker0
enable-dbus=no
ratelimit-interval-usec=1000000
ratelimit-burst=1000

[wide-area]
enable-wide-area=no

[publish]
publish-addresses=yes
publish-hinfo=yes
publish-workstation=no
publish-domain=yes
publish-aaaa-on-ipv4=no
publish-a-on-ipv6=no

[reflector]
enable-reflector=no

[rlimits]
